//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExmonSystem.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PRINTER_CUSTOM {
            get {
                return ((string)(this["PRINTER_CUSTOM"]));
            }
            set {
                this["PRINTER_CUSTOM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PRINTER_PARACOD {
            get {
                return ((string)(this["PRINTER_PARACOD"]));
            }
            set {
                this["PRINTER_PARACOD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PARACOD_CHK_COMPANY {
            get {
                return ((bool)(this["PARACOD_CHK_COMPANY"]));
            }
            set {
                this["PARACOD_CHK_COMPANY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PARACOD_CHK_PRICE {
            get {
                return ((bool)(this["PARACOD_CHK_PRICE"]));
            }
            set {
                this["PARACOD_CHK_PRICE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string COMPANY {
            get {
                return ((string)(this["COMPANY"]));
            }
            set {
                this["COMPANY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PRINTER_Roll {
            get {
                return ((string)(this["PRINTER_Roll"]));
            }
            set {
                this["PRINTER_Roll"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string COMPANYEn {
            get {
                return ((string)(this["COMPANYEn"]));
            }
            set {
                this["COMPANYEn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CompanyDetailsAr {
            get {
                return ((string)(this["CompanyDetailsAr"]));
            }
            set {
                this["CompanyDetailsAr"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CompanyDetailsEn {
            get {
                return ((string)(this["CompanyDetailsEn"]));
            }
            set {
                this["CompanyDetailsEn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CompanyPhons {
            get {
                return ((string)(this["CompanyPhons"]));
            }
            set {
                this["CompanyPhons"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CompanyTaxNumber {
            get {
                return ((string)(this["CompanyTaxNumber"]));
            }
            set {
                this["CompanyTaxNumber"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ar")]
        public string Language {
            get {
                return ((string)(this["Language"]));
            }
            set {
                this["Language"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool PropHReportsHeader {
            get {
                return ((bool)(this["PropHReportsHeader"]));
            }
            set {
                this["PropHReportsHeader"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int itemId {
            get {
                return ((int)(this["itemId"]));
            }
            set {
                this["itemId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int itemNo {
            get {
                return ((int)(this["itemNo"]));
            }
            set {
                this["itemNo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string itemName {
            get {
                return ((string)(this["itemName"]));
            }
            set {
                this["itemName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CheckAllowSaleNegativeQty {
            get {
                return ((bool)(this["CheckAllowSaleNegativeQty"]));
            }
            set {
                this["CheckAllowSaleNegativeQty"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CheckAllowSaleUnderCost {
            get {
                return ((bool)(this["CheckAllowSaleUnderCost"]));
            }
            set {
                this["CheckAllowSaleUnderCost"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CheckAllowBillEditDate {
            get {
                return ((bool)(this["CheckAllowBillEditDate"]));
            }
            set {
                this["CheckAllowBillEditDate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal PropValueServicePurchase {
            get {
                return ((decimal)(this["PropValueServicePurchase"]));
            }
            set {
                this["PropValueServicePurchase"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal PropValueServiceSales {
            get {
                return ((decimal)(this["PropValueServiceSales"]));
            }
            set {
                this["PropValueServiceSales"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal PropValueTaxPurchase {
            get {
                return ((decimal)(this["PropValueTaxPurchase"]));
            }
            set {
                this["PropValueTaxPurchase"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal PropValueTaxSales {
            get {
                return ((decimal)(this["PropValueTaxSales"]));
            }
            set {
                this["PropValueTaxSales"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CheckSaleTaxIncludPrice {
            get {
                return ((bool)(this["CheckSaleTaxIncludPrice"]));
            }
            set {
                this["CheckSaleTaxIncludPrice"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CheckPurchaseTaxIncludPrice {
            get {
                return ((bool)(this["CheckPurchaseTaxIncludPrice"]));
            }
            set {
                this["CheckPurchaseTaxIncludPrice"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CheckPurchaseAppTax {
            get {
                return ((bool)(this["CheckPurchaseAppTax"]));
            }
            set {
                this["CheckPurchaseAppTax"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CheckSalesAppTax {
            get {
                return ((bool)(this["CheckSalesAppTax"]));
            }
            set {
                this["CheckSalesAppTax"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string UnitName {
            get {
                return ((string)(this["UnitName"]));
            }
            set {
                this["UnitName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int BillId {
            get {
                return ((int)(this["BillId"]));
            }
            set {
                this["BillId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CheckItemCostUpdateWithPurchase {
            get {
                return ((bool)(this["CheckItemCostUpdateWithPurchase"]));
            }
            set {
                this["CheckItemCostUpdateWithPurchase"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int PropBAccountCash {
            get {
                return ((int)(this["PropBAccountCash"]));
            }
            set {
                this["PropBAccountCash"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int PropBAccountSales {
            get {
                return ((int)(this["PropBAccountSales"]));
            }
            set {
                this["PropBAccountSales"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int PropBAccountPurchase {
            get {
                return ((int)(this["PropBAccountPurchase"]));
            }
            set {
                this["PropBAccountPurchase"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int PropBAccountBank {
            get {
                return ((int)(this["PropBAccountBank"]));
            }
            set {
                this["PropBAccountBank"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int PropMainAccountCustomers {
            get {
                return ((int)(this["PropMainAccountCustomers"]));
            }
            set {
                this["PropMainAccountCustomers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int PropMainAccountSuplier {
            get {
                return ((int)(this["PropMainAccountSuplier"]));
            }
            set {
                this["PropMainAccountSuplier"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int PropMainAccountExpens {
            get {
                return ((int)(this["PropMainAccountExpens"]));
            }
            set {
                this["PropMainAccountExpens"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int PropMainAccountCashes {
            get {
                return ((int)(this["PropMainAccountCashes"]));
            }
            set {
                this["PropMainAccountCashes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int PropNumricPrintPos {
            get {
                return ((int)(this["PropNumricPrintPos"]));
            }
            set {
                this["PropNumricPrintPos"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int PropNumricPrintInvoice {
            get {
                return ((int)(this["PropNumricPrintInvoice"]));
            }
            set {
                this["PropNumricPrintInvoice"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PropLogoName {
            get {
                return ((string)(this["PropLogoName"]));
            }
            set {
                this["PropLogoName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\")]
        public string PropBackUpPath {
            get {
                return ((string)(this["PropBackUpPath"]));
            }
            set {
                this["PropBackUpPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool PropAutoBackupinClose {
            get {
                return ((bool)(this["PropAutoBackupinClose"]));
            }
            set {
                this["PropAutoBackupinClose"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Office 2016 Black")]
        public string ApplicationSkinName {
            get {
                return ((string)(this["ApplicationSkinName"]));
            }
            set {
                this["ApplicationSkinName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsInitialize {
            get {
                return ((bool)(this["IsInitialize"]));
            }
            set {
                this["IsInitialize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowSerialColumn {
            get {
                return ((bool)(this["ShowSerialColumn"]));
            }
            set {
                this["ShowSerialColumn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AllowPrescription {
            get {
                return ((bool)(this["AllowPrescription"]));
            }
            set {
                this["AllowPrescription"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MizanAllowUse {
            get {
                return ((bool)(this["MizanAllowUse"]));
            }
            set {
                this["MizanAllowUse"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public int MizanItemQty {
            get {
                return ((int)(this["MizanItemQty"]));
            }
            set {
                this["MizanItemQty"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int MizanItemlength {
            get {
                return ((int)(this["MizanItemlength"]));
            }
            set {
                this["MizanItemlength"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("90")]
        public int MizanStarts {
            get {
                return ((int)(this["MizanStarts"]));
            }
            set {
                this["MizanStarts"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PropActv {
            get {
                return ((string)(this["PropActv"]));
            }
            set {
                this["PropActv"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PropVerisonSleep {
            get {
                return ((string)(this["PropVerisonSleep"]));
            }
            set {
                this["PropVerisonSleep"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Propfree {
            get {
                return ((string)(this["Propfree"]));
            }
            set {
                this["Propfree"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1042")]
        public int VersonNo {
            get {
                return ((int)(this["VersonNo"]));
            }
            set {
                this["VersonNo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("15")]
        public decimal PropValueExpensesTax {
            get {
                return ((decimal)(this["PropValueExpensesTax"]));
            }
            set {
                this["PropValueExpensesTax"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int PropBExpensesTaxAccount {
            get {
                return ((int)(this["PropBExpensesTaxAccount"]));
            }
            set {
                this["PropBExpensesTaxAccount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Local")]
        public string ConType {
            get {
                return ((string)(this["ConType"]));
            }
            set {
                this["ConType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ln")]
        public string ConName {
            get {
                return ((string)(this["ConName"]));
            }
            set {
                this["ConName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CheckAllowSaleUnderLessPrice {
            get {
                return ((bool)(this["CheckAllowSaleUnderLessPrice"]));
            }
            set {
                this["CheckAllowSaleUnderLessPrice"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int PropBDiscountCustomerAccount {
            get {
                return ((int)(this["PropBDiscountCustomerAccount"]));
            }
            set {
                this["PropBDiscountCustomerAccount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int PropBDiscountSuplierAccount {
            get {
                return ((int)(this["PropBDiscountSuplierAccount"]));
            }
            set {
                this["PropBDiscountSuplierAccount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CheckItemPriceUpdateWithPurchase {
            get {
                return ((bool)(this["CheckItemPriceUpdateWithPurchase"]));
            }
            set {
                this["CheckItemPriceUpdateWithPurchase"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CheckUnitPriceUpdateWithItemPrice {
            get {
                return ((bool)(this["CheckUnitPriceUpdateWithItemPrice"]));
            }
            set {
                this["CheckUnitPriceUpdateWithItemPrice"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CheckAllowBillPurchaseEditDate {
            get {
                return ((bool)(this["CheckAllowBillPurchaseEditDate"]));
            }
            set {
                this["CheckAllowBillPurchaseEditDate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int QtyDecimalPlaces {
            get {
                return ((int)(this["QtyDecimalPlaces"]));
            }
            set {
                this["QtyDecimalPlaces"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int PriceDecimalPlaces {
            get {
                return ((int)(this["PriceDecimalPlaces"]));
            }
            set {
                this["PriceDecimalPlaces"] = value;
            }
        }
    }
}
