// <auto-generated />
namespace ExmonSystem.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class newex4 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(newex4));
        
        string IMigrationMetadata.Id
        {
            get { return "202305221630184_newex4"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
