// <auto-generated />
namespace ExmonSystem.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class new7 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(new7));
        
        string IMigrationMetadata.Id
        {
            get { return "202305251925492_new7"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
